---
name: Acortador de enlaces
locale: es
type: learning
beta: false
teacher_info: |2

  (Nota mental: se centró en el dominio y no en la aplicación)




    >> Hacé un diagrama de arquitectura. Debe tener
  Un nodo
  Un servidor
  Una base de datos
  Un actor
  La nubecita


  iaas vs paas
language: text
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
