---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Más de 0 y menos de 10^3
  checked: false
- value: Más de 10^3 y menos de 10^43
  checked: false
- value: Más de 10^43 y menos de 10^53
  checked: true
- value: Más de 10^53 y menos de 10^83
  checked: false
- value: Más de 10^83
  checked: false
