---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Menos de 10^3
  checked: false
- value: Menos de 10^43
  checked: false
- value: Menos de 10^53
  checked: true
- value: Menos de 10^83
  checked: false
- value: Mas de 10^83
  checked: false
