---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Más de 100 y menos de 10^6
  checked: false
- value: Más de 10^6 y menos de 10^9
  checked: false
- value: Más de 10^9 y menos de 10^13
  checked: true
- value: Más de 10^13 y menos de 10^19
  checked: false
- value: Más de 10^19
  checked: false
