---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Opción 1
  checked: false
- value: Opción 2
  checked: false
- value: Opción 3
  checked: true
