---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Usando FTP
  checked: false
- value: Usando Git
  checked: true
- value: Subiendo tus archivos desde una consola Web
  checked: false
